esphome:
  name: st7567s-display-test-8266

external_components:
  source: github://latonita/esphome-st7567s-display@main
  components: [st7567_base, st7567_i2c]

esp8266:
  board: nodemcuv2

logger:
    level: WARN

font:
 - file: "gfonts://Roboto"
   id: my_font
   size: 24

i2c:
  sda: D2
  scl: D1
  scan: true

    # Example minimal configuration entry
i2c:
  sda: D1
  scl: D2

display:
  - platform: st7567_i2c
    id: my_display
    lambda: |-
      it.print(0, 0, id(my_font), "Hello World!");
      
interval:
  - interval: 1h
    then:
      - lambda: id(my_display).request_refresh();

